version: '3.8'

services:
  nginx:
    image: nginx:1.17-alpine
    container_name: equip-nginx
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - ./src:/var/www/laravel_docker
      - ./nginx:/etc/nginx/conf.d
      - ./log:/var/log/nginx
    links:
      - php-fpm
    networks:
      - others_my-net

  php-fpm:
    container_name: equip-php-fpm
    build:
      context: ./php
    restart: unless-stopped
    ports:
      - "9000:9000"
    working_dir: /var/www/laravel_docker
    volumes:
      - ./src:/var/www/laravel_docker
    networks:
      - others_my-net
      
  mysql:
    image: mysql:5.7
    container_name: equip_db
    ports:
      - "3306:3306"
    volumes:
      - equip-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: my_base
      MYSQL_PASSWORD: my_base
    networks:
      - others_my-net
      
  mailhog:
    image: mailhog/mailhog
    logging:
      driver: 'none'
    ports:
      - 1025:1025
      - 8030:8025
    networks:
      - others_my-net
      
networks:
  others_my-net:
    external: true
    
volumes:
  equip-mysql-data:


